language: ruby
rvm:
- 2.1.5
before_install: gem install bundler
gemfile: Gemfile
script: make mutate
notifications:
  slack:
    secure: nPrklGv0vQsCH5GQ8Czhb9CPNnCUPnScgLcYSjsVpVTt1U36fxQ0vf/zAn5k8pYJ7Xf8EjgAfhScx9DIbv+gx57FpF4QUa9OmxBrnTCpOcCKnk6NGGdz3YA2uf+AoheSW4OTJO1AQYNE0qiHUmKCJBU/QDpVPsBYsUNMo2GK2ZJwsKnAynBRgAzkJn0gWxGEJ3XMVjYSUJu6wNhf4UhcTTo/xvVfXwDCANlQDR+bA9/Bv7S0fbpuwF5LIEp9ph+4UtEkp2J+/jOKa6O+UzqyMsH6agieNbweWsXTDX5c5Lz3NcV4pym/JqHcCyBGnD4ndDpI431NS9qmLzLPAHQeYqYqHTpZwWVR+Gx8Ui5cuZttvbZFsep2geRtQjZzJgPR/sFNi3T5AbWUqd+mpBzlPkdMfxxvAUWMvUIZ6uvLigJLPcdGpCyYIDECU2LKAhV4A+WZD2yLppjJ70G1SseZfYJCi0/hF95qmhdg+JNgK+yRXt6tvPgJmr3muOByfVjdXWVNipF7YvqJDQsUh1nZdVfkIEcWB4zkkXIApO3oolgC6gPrl1vUh90VPWl6tIJAl2UAbWFlK7Xfe8faGk7srhYZyUWfSVfgwSKxfxmghhAYjxnF4PQ7ih4e6Q8NqqdsCg2dfeEECTJUNSi2Mj8fu+O0g4U7Axu2j6wT+VJ7SGA=
env:
- CODECLIMATE_REPO_TOKEN=f50cdff1520f601555ff059f54f8c72bbac628850cc5a744de73c386602a45ae
