language: ruby
rvm:
  - 2.1.10
  - 2.2.5
  - 2.3.1
before_install: gem install bundler
gemfile: Gemfile
script: make mutate
env:
- CODECLIMATE_REPO_TOKEN=3af5c60b54fff033bf0dc1af4f26762647bcf3b78268a94d67ea9530b5b52a61
notifications:
  slack:
    secure: CFijr8ytPJGA5PqjABHTamy1b5YE0IoneBw0TemEFfatN4IYiTxRnItSmZDfVmgQLhK8EH5599j3cCsMPaC11Z10VKTCxZoxiLBJLmeVpAWPqTNL6MnHFSZ3ls/d5LkKCcbWlRKvqZpvtUW+PI7FuEWRT9ok/i1iabR5AwO1vwldKfcKgZII3PErDxIKzfIAQL45hVJsvkoTNPL0aOYnvtE6qBglCxJX6TcwAe7gwo+r6se/X0wI5gLGHz+t9NmH2PjEbG2iJ3YbrwXkAElI8TG3O4D9yUs7OaJ2yYDFs+oxseY4XwvKQtdKeu9QiFfexivLjB8FfUtgTlfmELbQ8bd3wltGxXjOdbGhR1bTHXiMtxwCJ8bB7hiDZFrYkpFn+vjmP/raXoD3o25GfEBE5dFtlm6ad+d+2rGpo9frbD3gQFYtx9LLEac2CkhCMoHAtsT3K6WqZ3VbvfG9K5iIhoGjLd3iWqsjZmFRSTrSdMskTwgochH6rx9UX1/p0MSPZ8gye7nAFMVkCoytogqJT9PAOPR+z7BfZHiD86UL+8LUrr1WneELJJDFgVZXdAV526mw/+6gsnNobj19PW4Ckgsxcz8kTzpepbmsFGGvFy6lIpIHdH8zvbOgIQlfaeLm/XQuvaudaqUtJzrNUskvon6B/f78CHV2zdUZWgCYIO0=
