name: aggregate_root
on:
  push:
    paths-ignore:
      - "railseventstore.org/**"
      - "contrib/**"
  pull_request:
    paths-ignore:
      - "railseventstore.org/**"
      - "contrib/**"
jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      GEM_NAME: aggregate_root
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: ruby-2.7
            gemfile: Gemfile
          - ruby: ruby-2.6
            gemfile: Gemfile
          - ruby: ruby-2.5
            gemfile: Gemfile
    steps:
      - uses: actions/checkout@v2
      - run: test -e ${{ matrix.gemfile }}.lock
        working-directory: ${{ env.GEM_NAME }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          working-directory: ${{ env.GEM_NAME }}
      - run: make test
        working-directory: ${{ env.GEM_NAME }}

  mutate:
    runs-on: ubuntu-20.04
    env:
      GEM_NAME: aggregate_root
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: ruby-2.7
            gemfile: Gemfile
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: test -e ${{ matrix.gemfile }}.lock
        working-directory: ${{ env.GEM_NAME }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          working-directory: ${{ env.GEM_NAME }}
      - run: make mutate-changes
        working-directory: ${{ env.GEM_NAME }}
