name: coverage
on:
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:
jobs:
  aggregate_root:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 180
    env:
      GEM_NAME: aggregate_root
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: ruby-2.7
            gemfile: Gemfile
            os: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: test -e ${{ matrix.gemfile }}.lock
        working-directory: ${{ env.GEM_NAME }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          working-directory: ${{ env.GEM_NAME }}
      - run: make mutate
        working-directory: ${{ env.GEM_NAME }}

  bounded_context:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    env:
      GEM_NAME: bounded_context
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: ruby-2.7
            gemfile: Gemfile
            os: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: test -e ${{ matrix.gemfile }}.lock
        working-directory: ${{ env.GEM_NAME }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          working-directory: ${{ env.GEM_NAME }}
      - run: make mutate
        working-directory: ${{ env.GEM_NAME }}

  rails_event_store_active_record:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    env:
      GEM_NAME: rails_event_store_active_record
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: ruby-2.7
            gemfile: Gemfile
            database: "sqlite3::memory:"
            datatype: binary
            os: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: test -e ${{ matrix.gemfile }}.lock
        working-directory: ${{ env.GEM_NAME }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          working-directory: ${{ env.GEM_NAME }}
      - run: make mutate
        working-directory: ${{ env.GEM_NAME }}

  ruby_event_store-rspec:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    env:
      GEM_NAME: ruby_event_store-rspec
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: ruby-2.7
            gemfile: Gemfile
            os: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: test -e ${{ matrix.gemfile }}.lock
        working-directory: ${{ env.GEM_NAME }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          working-directory: ${{ env.GEM_NAME }}
      - run: make mutate
        working-directory: ${{ env.GEM_NAME }}

  rails_event_store:
    runs-on: ubuntu-20.04
    timeout-minutes: 120
    env:
      GEM_NAME: rails_event_store
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: ruby-2.7
            gemfile: Gemfile
            os: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: test -e ${{ matrix.gemfile }}.lock
        working-directory: ${{ env.GEM_NAME }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          working-directory: ${{ env.GEM_NAME }}
      - run: make mutate
        working-directory: ${{ env.GEM_NAME }}

  ruby_event_store-browser:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    env:
      GEM_NAME: ruby_event_store-browser
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: ruby-2.7
            gemfile: Gemfile
            os: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: test -e ${{ matrix.gemfile }}.lock
        working-directory: ${{ env.GEM_NAME }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          working-directory: ${{ env.GEM_NAME }}
      - run: make mutate
        working-directory: ${{ env.GEM_NAME }}

  ruby_event_store:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    env:
      GEM_NAME: ruby_event_store
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: ruby-2.7
            gemfile: Gemfile
            os: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: test -e ${{ matrix.gemfile }}.lock
        working-directory: ${{ env.GEM_NAME }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          working-directory: ${{ env.GEM_NAME }}
      - run: make mutate
        working-directory: ${{ env.GEM_NAME }}
