name: dres_client
on:
  repository_dispatch:
    types:
      - script
  workflow_dispatch:
  schedule:
    - cron: "0 17 * * *"
  push:
    paths:
      - "contrib/dres_client/**"
      - "contrib/dres_rails/**"
      - ".github/workflows/dres_client.yml"
      - "support/**"
      - "!support/bundler/**"
      - "!support/ci/**"
  pull_request:
    types: [opened, reopened]
    paths:
      - "contrib/dres_client/**"
      - "contrib/dres_rails/**"
      - ".github/workflows/dres_client.yml"
      - "support/**"
      - "!support/bundler/**"
      - "!support/ci/**"
jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      WORKING_DIRECTORY: contrib/dres_client
      RUBY_VERSION: "${{ matrix.ruby_version }}"
      BUNDLE_GEMFILE: "${{ matrix.bundle_gemfile }}"
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby_version: ruby-3.1
            bundle_gemfile: Gemfile
          - ruby_version: ruby-3.0
            bundle_gemfile: Gemfile
    steps:
      - uses: actions/checkout@v3
      - run: test -e ${{ matrix.bundle_gemfile }}.lock
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true
          working-directory: ${{ env.WORKING_DIRECTORY }}
      - run: make test
        working-directory: ${{ env.WORKING_DIRECTORY }}
