name: rails_event_store_active_record
on:
  repository_dispatch:
    types:
      - script
  workflow_dispatch:
  push:
    paths-ignore:
      - "railseventstore.org/**"
      - "contrib/**"
  pull_request:
    types: [opened, reopened]
    paths-ignore:
      - "railseventstore.org/**"
      - "contrib/**"
jobs:
  test:
    runs-on: ${{ matrix.os }}
    env:
      WORKING_DIRECTORY: rails_event_store_active_record
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      DATABASE_URL: ${{ matrix.database }}
      DATA_TYPE: ${{ matrix.datatype }}
    services:
      postgres_11:
        image: postgres:11
        env:
          POSTGRES_DB: rails_event_store
          POSTGRES_PASSWORD: secret
        ports:
          - 10011:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      postgres_12:
        image: postgres:12
        env:
          POSTGRES_DB: rails_event_store
          POSTGRES_PASSWORD: secret
        ports:
          - 10012:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      mysql_5:
        image: mysql:5
        env:
          MYSQL_DATABASE: rails_event_store
          MYSQL_ROOT_PASSWORD: secret
        ports:
          - 10005:3306
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 5
      mysql_8:
        image: mysql:8
        env:
          MYSQL_DATABASE: rails_event_store
          MYSQL_ROOT_PASSWORD: secret
        ports:
          - 10008:3306
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 5
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: ruby-3.1
            gemfile: Gemfile
            os: ubuntu-20.04
            database: sqlite3:db.sqlite3
            datatype: binary
          - ruby: ruby-3.1
            gemfile: Gemfile.rails_6_1
            os: ubuntu-20.04
            database: sqlite3:db.sqlite3
            datatype: binary
          - ruby: ruby-3.0
            gemfile: Gemfile
            os: ubuntu-20.04
            database: sqlite3:db.sqlite3
            datatype: binary
          - ruby: ruby-3.0
            gemfile: Gemfile.rails_6_1
            os: ubuntu-20.04
            database: sqlite3:db.sqlite3
            datatype: binary
          - ruby: ruby-2.7
            gemfile: Gemfile.rails_6_1
            os: ubuntu-20.04
            database: sqlite3:db.sqlite3
            datatype: binary
          - ruby: ruby-2.7
            gemfile: Gemfile.rails_6_0
            os: ubuntu-20.04
            database: sqlite3:db.sqlite3
            datatype: binary
          - ruby: ruby-3.1
            gemfile: Gemfile
            os: ubuntu-20.04
            database: postgres://postgres:secret@localhost:10012/rails_event_store?pool=5
            datatype: binary
          - ruby: ruby-3.1
            gemfile: Gemfile
            os: ubuntu-20.04
            database: postgres://postgres:secret@localhost:10012/rails_event_store?pool=5
            datatype: json
          - ruby: ruby-3.1
            gemfile: Gemfile
            os: ubuntu-20.04
            database: postgres://postgres:secret@localhost:10012/rails_event_store?pool=5
            datatype: jsonb
          - ruby: ruby-3.1
            gemfile: Gemfile
            os: ubuntu-20.04
            database: postgres://postgres:secret@localhost:10011/rails_event_store?pool=5
            datatype: binary
          - ruby: ruby-3.1
            gemfile: Gemfile
            os: ubuntu-20.04
            database: mysql2://root:secret@127.0.0.1:10008/rails_event_store?pool=5
            datatype: binary
          - ruby: ruby-3.1
            gemfile: Gemfile
            os: ubuntu-20.04
            database: mysql2://root:secret@127.0.0.1:10005/rails_event_store?pool=5
            datatype: binary
          - ruby: ruby-2.7
            gemfile: Gemfile
            os: ubuntu-20.04
            database: sqlite3:db.sqlite3
            datatype: binary
    steps:
      - uses: actions/checkout@v2
      - run: test -e ${{ matrix.gemfile }}.lock
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: false
          working-directory: ${{ env.WORKING_DIRECTORY }}
      - run: make install test
        working-directory: ${{ env.WORKING_DIRECTORY }}

  mutate:
    runs-on: ${{ matrix.os }}
    env:
      WORKING_DIRECTORY: rails_event_store_active_record
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      DATABASE_URL: ${{ matrix.database }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: ruby-3.1
            gemfile: Gemfile
            os: ubuntu-20.04
            database: "sqlite3::memory:"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: test -e ${{ matrix.gemfile }}.lock
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          working-directory: ${{ env.WORKING_DIRECTORY }}
      - run: make mutate-changes
        working-directory: ${{ env.WORKING_DIRECTORY }}
