name: ruby_event_store-sequel_test
on:
  workflow_dispatch:
  repository_dispatch:
    types:
    - script
  push:
    branches:
    - master
    paths:
    - contrib/ruby_event_store-sequel/**
    - ".github/workflows/ruby_event_store-sequel_test.yml"
    - support/**
    - "!support/bundler/**"
    - "!support/ci/**"
  pull_request:
    paths:
    - contrib/ruby_event_store-sequel/**
    - ".github/workflows/ruby_event_store-sequel_test.yml"
    - support/**
    - "!support/bundler/**"
    - "!support/ci/**"
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    env:
      WORKING_DIRECTORY: contrib/ruby_event_store-sequel
      RUBY_VERSION: "${{ matrix.ruby_version }}"
      BUNDLE_GEMFILE: "${{ matrix.bundle_gemfile }}"
      DATABASE_URL: "${{ matrix.database_url }}"
      DATA_TYPE: "${{ matrix.data_type }}"
    services:
      postgres_13:
        image: postgres:13
        env:
          POSTGRES_DB: rails_event_store
          POSTGRES_PASSWORD: secret
        ports:
        - 10013:5432
        options: --health-cmd "pg_isready" --health-interval 10s --health-timeout 5s --health-retries 5
      postgres_17:
        image: postgres:17
        env:
          POSTGRES_DB: rails_event_store
          POSTGRES_PASSWORD: secret
        ports:
        - 10017:5432
        options: --health-cmd "pg_isready" --health-interval 10s --health-timeout 5s --health-retries 5
      mysql_8:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: rails_event_store
          MYSQL_ROOT_PASSWORD: secret
        ports:
        - 10080:3306
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 5
      mysql_8_4:
        image: mysql:8.4
        env:
          MYSQL_DATABASE: rails_event_store
          MYSQL_ROOT_PASSWORD: secret
        ports:
        - 10084:3306
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 5
    strategy:
      fail-fast: false
      matrix:
        include:
        - ruby_version: ruby-3.4
          bundle_gemfile: Gemfile
          database_url: sqlite:db.sqlite3
          data_type: text
        - ruby_version: ruby-3.3
          bundle_gemfile: Gemfile
          database_url: sqlite:db.sqlite3
          data_type: text
        - ruby_version: ruby-3.2
          bundle_gemfile: Gemfile
          database_url: sqlite:db.sqlite3
          data_type: text
        - ruby_version: ruby-3.4
          bundle_gemfile: Gemfile
          database_url: postgres://postgres:secret@localhost:10017/rails_event_store
          data_type: text
        - ruby_version: ruby-3.4
          bundle_gemfile: Gemfile
          database_url: postgres://postgres:secret@localhost:10013/rails_event_store
          data_type: text
        - ruby_version: ruby-3.4
          bundle_gemfile: Gemfile
          database_url: postgres://postgres:secret@localhost:10017/rails_event_store
          data_type: json
        - ruby_version: ruby-3.4
          bundle_gemfile: Gemfile
          database_url: postgres://postgres:secret@localhost:10017/rails_event_store
          data_type: jsonb
        - ruby_version: ruby-3.4
          bundle_gemfile: Gemfile
          database_url: mysql2://root:secret@127.0.0.1:10084/rails_event_store
          data_type: text
        - ruby_version: ruby-3.4
          bundle_gemfile: Gemfile
          database_url: mysql2://root:secret@127.0.0.1:10080/rails_event_store
          data_type: text
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - run: test -e ${{ env.BUNDLE_GEMFILE }}.lock
      working-directory: "${{ env.WORKING_DIRECTORY }}"
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ env.RUBY_VERSION }}"
        bundler-cache: true
        working-directory: "${{ env.WORKING_DIRECTORY }}"
    - run: make test
      working-directory: "${{ env.WORKING_DIRECTORY }}"
      env:
        RUBYOPT: "--enable-frozen-string-literal"