name: ruby_event_store-outbox
on:
  push:
    paths:
      - "contrib/ruby_event_store-outbox/**"
      - ".github/workflows/ruby_event_store-outbox.yml"
      - "support/**"
  pull_request:
    types: [opened, reopened]
    paths:
      - "contrib/ruby_event_store-outbox/**"
      - ".github/workflows/ruby_event_store-outbox.yml"
      - "support/**"
jobs:
  test:
    runs-on: ${{ matrix.os }}
    env:
      WORKING_DIRECTORY: contrib/ruby_event_store-outbox
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      DATABASE_URL: ${{ matrix.database }}
    services:
      redis:
        image: redis:6
        ports:
          - 6379:6379
      mysql_56:
        image: mysql:5.6
        env:
          MYSQL_DATABASE: rails_event_store
          MYSQL_ROOT_PASSWORD: secret
        ports:
          - 10056:3306
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 5
      mysql_57:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: rails_event_store
          MYSQL_ROOT_PASSWORD: secret
        ports:
          - 10057:3306
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 5
      mysql_80:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: rails_event_store
          MYSQL_ROOT_PASSWORD: secret
        ports:
          - 10080:3306
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 5
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: ruby-3.0
            gemfile: Gemfile
            os: ubuntu-20.04
            database: sqlite3:db.sqlite3
          - ruby: ruby-3.0
            gemfile: Gemfile.rails_6_0
            os: ubuntu-20.04
            database: sqlite3:db.sqlite3
          - ruby: ruby-2.6
            gemfile: Gemfile.rails_5_2
            os: ubuntu-20.04
            database: sqlite3:db.sqlite3
          - ruby: ruby-2.7
            gemfile: Gemfile
            os: ubuntu-20.04
            database: sqlite3:db.sqlite3
          - ruby: ruby-2.6
            gemfile: Gemfile
            os: ubuntu-20.04
            database: sqlite3:db.sqlite3
          - ruby: ruby-3.0
            gemfile: Gemfile
            os: ubuntu-20.04
            database: mysql2://root:secret@0.0.0.0:10056/rails_event_store
          - ruby: ruby-3.0
            gemfile: Gemfile
            os: ubuntu-20.04
            database: mysql2://root:secret@0.0.0.0:10057/rails_event_store
          - ruby: ruby-3.0
            gemfile: Gemfile
            os: ubuntu-20.04
            database: mysql2://root:secret@0.0.0.0:10080/rails_event_store
          - ruby: ruby-3.0
            gemfile: Gemfile.sidekiq_5_2
            os: ubuntu-20.04
            database: sqlite3:db.sqlite3
    steps:
      - uses: actions/checkout@v2
      - run: test -e ${{ matrix.gemfile }}.lock
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          working-directory: ${{ env.WORKING_DIRECTORY }}
      - run: make test
        working-directory: ${{ env.WORKING_DIRECTORY }}

  mutate:
    runs-on: ${{ matrix.os }}
    env:
      WORKING_DIRECTORY: contrib/ruby_event_store-outbox
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      DATABASE_URL: ${{ matrix.database }}
      REDIS_URL: redis://localhost:6379/0
      MUTANT_JOBS: 1
    services:
      redis:
        image: redis:6
        ports:
          - 6379:6379
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: ruby-3.0
            gemfile: Gemfile
            os: ubuntu-20.04
            database: "sqlite3::memory:"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: test -e ${{ matrix.gemfile }}.lock
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          working-directory: ${{ env.WORKING_DIRECTORY }}
      - run: make mutate-changes
        working-directory: ${{ env.WORKING_DIRECTORY }}
