name: ruby_event_store-rom
on:
  push:
    paths:
      - "contrib/ruby_event_store-rom/**"
      - ".github/workflows/ruby_event_store-rom.yml"
      - "support/**"
      - "Gemfile.shared"
  pull_request:
    types: [opened, reopened]
    paths:
      - "contrib/ruby_event_store-rom/**"
      - ".github/workflows/ruby_event_store-rom.yml"
      - "support/**"
      - "Gemfile.shared"
jobs:
  test:
    runs-on: ${{ matrix.os }}
    env:
      WORKING_DIRECTORY: contrib/ruby_event_store-rom
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      DATABASE_URL: ${{ matrix.database }}
      DATA_TYPE: ${{ matrix.datatype }}
    services:
      postgres_11:
        image: postgres:11
        env:
          POSTGRES_DB: rails_event_store
          POSTGRES_PASSWORD: secret
        ports:
          - 10011:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      postgres_12:
        image: postgres:12
        env:
          POSTGRES_DB: rails_event_store
          POSTGRES_PASSWORD: secret
        ports:
          - 10012:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      mysql_5:
        image: mysql:5
        env:
          MYSQL_DATABASE: rails_event_store
          MYSQL_ROOT_PASSWORD: secret
        ports:
          - 10005:3306
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 5
      mysql_8:
        image: mysql:8
        env:
          MYSQL_DATABASE: rails_event_store
          MYSQL_ROOT_PASSWORD: secret
        ports:
          - 10008:3306
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 5
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: ruby-3.0
            gemfile: Gemfile
            database: sqlite:db.sqlite3
            datatype: text
          - ruby: ruby-2.7
            gemfile: Gemfile
            database: sqlite:db.sqlite3
            os: ubuntu-20.04
            datatype: text
          - ruby: ruby-2.7
            gemfile: Gemfile
            database: postgres://postgres:secret@localhost:10012/rails_event_store?pool=5
            os: ubuntu-20.04
            datatype: text
          - ruby: ruby-2.7
            gemfile: Gemfile
            os: ubuntu-20.04
            database: postgres://postgres:secret@localhost:10012/rails_event_store?pool=5
            datatype: json
          - ruby: ruby-2.7
            gemfile: Gemfile
            os: ubuntu-20.04
            database: postgres://postgres:secret@localhost:10012/rails_event_store?pool=5
            datatype: jsonb
          - ruby: ruby-2.7
            gemfile: Gemfile
            os: ubuntu-20.04
            database: postgres://postgres:secret@localhost:10011/rails_event_store?pool=5
            datatype: text
          - ruby: ruby-2.7
            gemfile: Gemfile
            os: ubuntu-20.04
            database: mysql2://root:secret@127.0.0.1:10008/rails_event_store?pool=5
            datatype: text
          - ruby: ruby-2.7
            gemfile: Gemfile
            os: ubuntu-20.04
            database: mysql2://root:secret@127.0.0.1:10005/rails_event_store?pool=5
            datatype: text
          - ruby: ruby-2.6
            gemfile: Gemfile
            os: ubuntu-20.04
            database: sqlite:db.sqlite3
            datatype: text
    steps:
      - uses: actions/checkout@v2
      - run: test -e ${{ matrix.gemfile }}.lock
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          working-directory: ${{ env.WORKING_DIRECTORY }}
      - run: make test
        working-directory: ${{ env.WORKING_DIRECTORY }}

  mutate:
    runs-on: ${{ matrix.os }}
    env:
      WORKING_DIRECTORY: contrib/ruby_event_store-rom
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      DATABASE_URL: ${{ matrix.database }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: ruby-2.7
            gemfile: Gemfile
            os: ubuntu-20.04
            database: "sqlite::memory:"
            datatype: text
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: test -e ${{ matrix.gemfile }}.lock
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          working-directory: ${{ env.WORKING_DIRECTORY }}
      - run: make mutate-changes
        working-directory: ${{ env.WORKING_DIRECTORY }}
