name: ruby_event_store-newrelic
on:
  push:
    paths:
      - "contrib/ruby_event_store-newrelic/**"
      - ".github/workflows/ruby_event_store-newrelic.yml"
      - "support/**"
  pull_request:
    types: [opened, reopened]
    paths:
      - "contrib/ruby_event_store-newrelic/**"
      - ".github/workflows/ruby_event_store-newrelic.yml"
      - "support/**"
jobs:
  test:
    runs-on: ${{ matrix.os }}
    env:
      WORKING_DIRECTORY: contrib/ruby_event_store-newrelic
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      DATABASE_URL: ${{ matrix.database }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: ruby-3.0
            gemfile: Gemfile
            os: ubuntu-20.04
          - ruby: ruby-2.7
            gemfile: Gemfile
            os: ubuntu-20.04
          - ruby: ruby-2.6
            gemfile: Gemfile
            os: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: test -e ${{ matrix.gemfile }}.lock
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          working-directory: ${{ env.WORKING_DIRECTORY }}
      - run: make test
        working-directory: ${{ env.WORKING_DIRECTORY }}

  mutate:
    runs-on: ${{ matrix.os }}
    env:
      WORKING_DIRECTORY: contrib/ruby_event_store-newrelic
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      DATABASE_URL: ${{ matrix.database }}
      MUTANT_JOBS: 1
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: ruby-3.0
            gemfile: Gemfile
            os: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: test -e ${{ matrix.gemfile }}.lock
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          working-directory: ${{ env.WORKING_DIRECTORY }}
      - run: make mutate-changes
        working-directory: ${{ env.WORKING_DIRECTORY }}
